// vidkit /*@VERSION@*/ — type declarations for the page API (window.vk). GENERATED by `npm run docs` from
// scripts/docs/vk.d.ts + the live registry: do not edit docs/vk.d.ts by hand. Name unions are open
// (`| (string & {})`) because plugins can register more; strict mode / `vk lint` reject unknown names.
// Full parameter schemas: docs/api.json or vk.list(kind, {detail:true}) / vk.describe(kind, name) in a page.

export type FxName = /*@NAMES:fx@*/ string;
/** one fx or several space-separated ('up blur'); false = no entrance */
export type Fx = FxName | `${FxName} ${string}` | false;
export type TransitionName = /*@NAMES:transitions@*/ string;
/** 'name' or 'name:seconds' or an object */
export type Transition = TransitionName | `${TransitionName}:${number}` | { type: TransitionName; d?: number; ease?: Ease; focal?: { x: number; y: number } };
export type TextureName = /*@NAMES:textures@*/ string;
export type BackgroundName = /*@NAMES:backgrounds@*/ string;
export type ThemeName = /*@NAMES:themes@*/ string;
export type FormatName = /*@NAMES:formats@*/ string;
export type StyleName = /*@NAMES:styles@*/ string;
export type SoundName = /*@NAMES:sounds@*/ string;
export type EaseName = /*@NAMES:eases@*/ string;
export type Ease = EaseName | `cubic-bezier(${string})` | `spring(${string})` | `steps(${number})` | ((p: number) => number);
export type MaterialName = /*@NAMES:materials@*/ string;
export type BlockName = /*@NAMES:blocks@*/ string;
export type ThreeMaterialName = /*@NAMES:threeMaterials@*/ string;
export type ThreeRigName = /*@NAMES:threeRigs@*/ string;
export type ThreeProduct = /*@THREE_PRODUCTS@*/ string;
export type ThreeGrade = /*@THREE_GRADES@*/ string;

/** scene-local seconds, 'b:8' (beat 8), 'm:2' (measure), '+0.3' (after the previous element) */
export type Time = number | string;
export type Kind = 'fx' | 'transitions' | 'textures' | 'backgrounds' | 'blocks' | 'eases' | 'themes' | 'formats' | 'sounds' | 'materials' | 'styles' | 'three' | 'threeMaterials' | 'threeRigs';

export interface ParamSchema { type: string; default?: unknown; range?: [number, number]; values?: string[]; description?: string }
export interface Entry { name: string; description: string; params: Record<string, ParamSchema>; example: string | null; aliases?: string[]; aliasOf?: string; lazy?: boolean; requires?: string; source: 'builtin' | 'plugin'; [k: string]: unknown }

export interface VideoOptions {
  format?: FormatName; w?: number; h?: number; fps?: number;
  theme?: ThemeName | { extends?: ThemeName; mode?: 'dark' | 'light'; modes?: Record<string, Record<string, string>> };
  style?: StyleName | string | string[] | Record<string, string>;
  transition?: Transition; push?: number; ease?: Ease;
  texture?: Partial<Record<TextureName, object | number | boolean>>;
  bpm?: number; beatOffset?: number; beats?: number[] | string;
  music?: string; musicStart?: number; voice?: object | string; captions?: [number, number, string][] | string; karaoke?: 'sweep' | 'on' | 'pop';
  mix?: { lufs?: number; duck?: number; fadeOut?: number }; autoSfx?: boolean; score?: [number, SoundName, number?, number?][];
  motionBlur?: { shutter: string | number; samples: number }; cover?: object; fadeOut?: number; seed?: number;
  /** unknown names throw with did-you-mean; Math.random() during a frame throws (vk peek/qa/render default) */
  strict?: boolean;
  /** cheap preview path (vk.three: res .35, aa 1, no DOF / bloom) — vk peek/render --draft */
  draft?: boolean;
  manual?: boolean; bake?: boolean; title?: string; [k: string]: unknown;
}
export interface SceneOptions {
  bg?: 'dark' | 'light' | 'accent' | string | ({ type: BackgroundName } & Record<string, unknown>) | Array<string | object>;
  mode?: 'dark' | 'light' | 'accent'; transition?: Transition; cap?: string | string[] | [number, number, string][];
  camera?: { t: Time; x?: number; y?: number; s?: number; r?: number; ease?: Ease }[]; shots?: object[];
  push?: number; shake?: { t: Time; amp?: number; d?: number }[]; texture?: Partial<Record<TextureName, object | number>>;
  layout?: 'center' | 'left' | 'top' | 'bottom'; sfx?: boolean; vo?: string | string[]; hold?: number; snap?: string; [k: string]: unknown;
}
export interface NodeOptions {
  at?: Time; fx?: Fx; d?: number; ease?: Ease; each?: number; out?: Time; outFx?: Fx; sfx?: SoundName;
  size?: number | 'h1' | 'h2' | 'h3' | 'body' | 'small' | string; color?: string; bg?: string; weight?: number;
  font?: 'display' | 'mono' | 'sans' | 'serif' | 'condensed' | string; align?: 'left' | 'center' | 'right';
  /** ≤ 1 = fraction of the frame, > 1 = px at 720p */
  w?: number | string; maxW?: number | string; mt?: number | string;
  pos?: { x?: number | string; y?: number | string; right?: number | string; bottom?: number | string; w?: number | string; h?: number | string; anchor?: 'center' | 'top' };
  fixed?: boolean; class?: string; id?: string; style?: string | Record<string, string>;
  /** per-frame hook — must depend on time only */
  on?: (el: HTMLElement, local: number, p: number, t: number) => void;
  [k: string]: unknown;
}
/** an element description; built when the scene is created */
export interface VNode { o: NodeOptions; kind: string; build(ctx: unknown): Element | null }

export interface FrameInfo { t: number; W: number; H: number; fps: number; frame: number; frameT: number; beats: unknown; video: Video }
export type DrawFn = (g: CanvasRenderingContext2D, local: number, info: FrameInfo) => void;

export interface Scene {
  index: number; name: string; start: number; dur: number; el: HTMLElement;
  time(v: Time): number;
  /** per-frame callback: pure function of time */
  on(fn: (local: number, p: number, t: number) => void): Scene;
  tween(target: Element | Element[] | string, o: { t?: Time; d?: number; from?: object; to?: object; ease?: Ease; each?: number }): Scene;
  fx(target: Element | Element[] | string, fx: Fx, o?: object): Scene;
  canvas(draw: DrawFn, o?: { z?: 'back' | 'front'; zIndex?: number; blend?: string; motionBlur?: boolean | object }): unknown;
  paint(painters: DrawFn | DrawFn[], o?: object): unknown;
  webgl(o: { frag: string; z?: 'back' | 'front'; uniforms?: object }): unknown;
  gl(effects: unknown[], o?: object): unknown;
  /** vk.three (needs dist/vidkit-three.js): setup(ctx) → update(localT, info) | Promise */
  three(setup: ((ctx: ThreeCtx) => unknown) | ThreeModule | ThreeModule[], update?: ((lt: number, info: object) => void) | ThreeLayerOptions, opts?: ThreeLayerOptions): unknown;
  camera(keys: object[]): Scene; push(amount: number): Scene; shake(t: Time, o?: object): Scene; beatZoom(amount?: number, o?: object): Scene;
  add(...nodes: VNode[]): Scene; html(str: string, o?: { flow?: boolean; fixed?: boolean }): HTMLElement | HTMLElement[];
  texture(name: TextureName, o?: object): Scene; sfx(t: Time, name: SoundName, gain?: number, freq?: number): Scene;
  [k: string]: unknown;
}
export interface Video { W: number; H: number; fps: number; duration: number; strict: boolean; draft: boolean; scenes: Scene[]; style?: unknown; render(t: number): void; three(...a: unknown[]): unknown; canvas(draw: DrawFn, o?: object): unknown; [k: string]: unknown }

export interface ThreeCtx { THREE: any; scene: any; camera: any; renderer: any; rand: () => number; load: Record<string, (url: string, o?: object) => Promise<any>>; assets: Record<string, any>; layer: unknown; draft: boolean }
export interface ThreeModule { setup?: (ctx: ThreeCtx) => unknown; update?: (lt: number, info: object) => void }
export type ThreeLookPreset = /*@THREE_LOOKS@*/ string;
export type ThreeLookPass = { type: /*@THREE_LOOK_PASSES@*/ string; [param: string]: unknown };
/** preset name | pass list | {preset, <pass>: {…} | false} */
export type ThreeLook = ThreeLookPreset | ThreeLookPass[] | ({ preset?: ThreeLookPreset; passes?: ThreeLookPass[] } & Record<string, unknown>);
export interface ThreeLayerOptions {
  res?: number; aa?: number; motionBlur?: boolean | { shutter: string | number; samples: number };
  camera?: ((t: number) => { pos: number[]; target?: number[]; fov?: number; roll?: number }) | { pos: number[]; target?: number[]; fov?: number };
  fov?: number; background?: string | number; assets?: Record<string, string>; seed?: number; z?: 'back' | 'front'; rect?: number[];
  post?: { exposure?: number; tone?: 'aces' | 'none'; bloom?: false | { strength?: number; threshold?: number; knee?: number; radius?: number }; grade?: ThreeGrade | object; vignette?: number; grain?: number; ca?: number; dof?: boolean | { focus?: number; aperture?: number; maxBlur?: number }; fade?: number; fadeColor?: string; look?: ThreeLook };
  /** NPR look chain (same as post.look) */
  look?: ThreeLook;
  key?: (lt: number) => string;
}

type Factory = (text: string, o?: NodeOptions) => VNode;
export interface VK {
  version: string;
  video(cfg?: VideoOptions): Video;
  scene(name: string, dur: number | 'auto' | string, opts: SceneOptions, nodes: VNode[] | ((sc: Scene, v: Video) => void)): Scene;
  scene(name: string, dur: number | 'auto' | string, nodes: VNode[] | ((sc: Scene, v: Video) => void)): Scene;
  title: Factory; h2: Factory; sub: Factory; text: Factory; small: Factory; label: Factory; hero: Factory; badge: Factory;
  stack(lines: string[], o?: NodeOptions): VNode;
  row(nodes: VNode[], o?: NodeOptions): VNode; col(nodes: VNode[], o?: NodeOptions): VNode; grid(nodes: VNode[], o?: NodeOptions & { cols?: number }): VNode;
  split(left: VNode, right: VNode, o?: NodeOptions & { ratio?: number }): VNode; spacer(o?: NodeOptions): VNode;
  html(str: string, o?: NodeOptions): VNode; svg(markup: string, o?: NodeOptions): VNode; el(build: (ctx: any) => Element, o?: NodeOptions): VNode;
  node(o: NodeOptions, build: (ctx: any, o: NodeOptions) => Element, defaultFx?: Fx): VNode;
  json(src: string): any;
  /** registry: names (no options) · schemas ({detail:true}) · kinds (no args) */
  list(): Kind[]; list(kind: Kind | string): string[]; list(kind: Kind | string, o: { detail: true; all?: boolean }): Entry[];
  describe(kind: Kind | string, name: string): Entry; names(kind: Kind | string): string[]; suggest(name: string, valid: string[]): string[];
  readonly strict: boolean; setStrict(on: boolean): boolean;
  use(plugin: object | ((vk: VK, opts?: object) => void), opts?: object): VK;
  register(kind: Kind | 'layers' | 'hooks', name: string, impl: unknown, meta?: { description?: string; params?: Record<string, string | ParamSchema>; example?: string }): void;
  // deterministic helpers — use these instead of Math.random / clocks inside frame code
  hash(i: number): number; hash2(a: number, b: number): number; rand(seed: number): () => number; mulberry32(seed: number): () => number;
  noise1(x: number): number; noise2(x: number, y: number): number; hrange(i: number, a: number, b: number): number; hpick<T>(i: number, list: T[]): T;
  clamp(x: number, a: number, b: number): number; clamp01(x: number): number; lerp(a: number, b: number, p: number): number;
  progress(t: number, t0: number, d: number, ease?: Ease): number; seg(t: number, t0: number, t1: number): number;
  /** kf(t, [[t0, v0], [t1, v1], …], ease) */ kf(t: number, keys: [number, number, Ease?][], ease?: Ease): number; window01(t: number, a: number, b: number, din?: number, dout?: number): number;
  getEase(e: Ease): (p: number) => number; ease: Record<EaseName, (p: number) => number>;
  beat(n: number): number; pulse(t: number, k?: number, every?: number): number; onBeat(t: number, o?: { unit?: 'beat' | 'bar' | 'onset'; k?: number; every?: number }): number;
  style: ((spec: StyleName | string | object) => unknown) & { list(): { id: string; name: string; tags?: string[] }[]; get(id: StyleName): unknown; register(data: object, factory?: object | ((vk: VK) => object)): unknown; normalize(data: object): object; validate(data: object): { ok: boolean; errors: string[] }; mix(a: object, b: object, w?: number, o?: object): object; fork(a: object, o?: object): object; matchBase(prompt: string): string; ids: string[]; load(id: string, o?: object): Promise<unknown>; loadAll(o?: object): Promise<string[]> };
  three: { turntable(o?: object): ThreeModule; particles(o?: object): ThreeModule; product(name: ThreeProduct, o?: object): any; materials: Record<ThreeMaterialName, (o?: object) => any>; rig: Record<ThreeRigName, (o?: object) => (t: number) => object>; mixer(root: any, clips: any[], o?: { once?: boolean; timeline?: { t: number; clip: string; fade?: number; speed?: number; loop?: boolean; offset?: number; weight?: number }[]; weights?: Record<string, number | ((t: number) => number)> }): { at(t: number, weights?: Record<string, number>): unknown };
    look: ((spec: ThreeLook, post?: object) => object) & { passes: Record<string, { doc: string; d: object }>; presets: Record<ThreeLookPreset, ThreeLookPass[]>; expand(spec: ThreeLook): ThreeLookPass[] };
    diorama(o?: { kind?: /*@THREE_DIORAMAS@*/ string; [k: string]: unknown }): ThreeModule; shaderPlate(o?: { preset?: /*@THREE_PLATES@*/ string; sdf?: string; shade?: string; background?: string; glsl?: string; uniforms?: object; [k: string]: unknown }): ThreeModule;
    text3d(o?: { text?: string; font?: /*@THREE_FONTS3D@*/ string; in?: /*@THREE_LETTERS@*/ string | object; out?: string | object; [k: string]: unknown }): ThreeModule;
    sim<S = any>(o: { init(rand: () => number): S; step(state: S, dt: number, t: number, i: number): void; dt?: number; every?: number; duration?: number; key?: string; seed?: number }): { at(t: number): S; ready(ctx: object): Promise<unknown>; module(o: { setup?(ctx: object, sim: unknown): unknown; render(state: S, t: number, info: object): void }): ThreeModule };
    terrain(o?: object): ThreeModule & { heightAt?(x: number, z: number): number }; globe(o?: object): ThreeModule; model(url: string, o?: object): ThreeModule; frameIdx(t: number, fps: number): number; [k: string]: any };
  gl: Record<string, any>; mg: Record<string, any>; accents: Record<string, (o?: object) => DrawFn>; ui: Record<string, (o?: object) => VNode>;
  [k: string]: any;
}
declare global { const vk: VK; interface Window { vk: VK } }
export {};
