// vk make --style ink[,papercut.chars] --story story.md -o examples/<slug>/ [--name slug] [--tts] [--render] [--force]
//   Story (markdown or JSON, see src/styles/story.js) → a styled, narrated film page wired to vk.film():
//   <dir>/<slug>.html (story inlined as editable data) + <dir>/story.md (source copy).
//   --tts runs `vk tts` (edge-tts narration + word timings + lip-sync envelope); --render renders out/<slug>.mp4.
import { parseArgs, ROOT, fs, path } from './lib.mjs';
import { parseStory } from '../src/styles/story.js';

export default async function make(argv) {
  const opt = parseArgs(argv, ['tts', 'render', 'force']);
  const storyFile = opt.story || opt._[0];
  if (!storyFile || !fs.existsSync(storyFile)) throw new Error('usage: vk make --style <id>[,<id>] --story story.md -o examples/<slug>/ [--tts] [--render]');
  const src = fs.readFileSync(storyFile, 'utf8'), story = parseStory(src);
  const styleArg = opt.style || story.style || 'papercut';
  const styles = String(styleArg).split(/[,+]/).map(s => s.trim()).filter(Boolean);
  const known = fs.readdirSync(path.join(ROOT, 'styles')).filter(d => fs.existsSync(path.join(ROOT, 'styles', d, 'style.json')));
  for (const s of styles) { const id = s.split(/[.:/]|-(?=(bg|background|world|chars?|characters?|type|text|titles?|motion|camera|sound|music|audio|fx|effects)$)/)[0]; if (!known.includes(id)) throw new Error(`unknown style "${s}" (have: ${known.join(', ')})`); }
  const dir = path.resolve(opt.out || path.join('examples', opt.name || path.basename(storyFile, path.extname(storyFile))));
  const slug = opt.name || path.basename(dir);
  fs.mkdirSync(dir, { recursive: true });
  const page = path.join(dir, slug + '.html');
  if (fs.existsSync(page) && !opt.force) throw new Error('exists: ' + page + ' (use --force to overwrite)');
  if (!story.scenes.length) throw new Error('story has no scenes (## heading per scene)');
  const rel = path.relative(dir, path.join(ROOT, 'dist/vidkit.js')).split(path.sep).join('/');
  const spec = styles.length === 1 ? `'${styles[0]}'` : JSON.stringify(styles).replace(/"/g, "'");
  const json = JSON.stringify({ ...story, style: undefined }, null, 1).replace(/<\/script/gi, '<\\/script');
  fs.writeFileSync(page, `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><title>${esc(story.title || slug)}</title></head>
<body>
<script src="${rel}"></script>
<script>
// Generated by \`vk make --style ${styles.join(',')} --story ${path.basename(storyFile)}\`. Edit STORY freely:
//   scenes[].setting  — world words (vk.style.parseSetting: mountain/field/village/river/city/palace/forest/garden ·
//                       dawn/day/dusk/night · pine/willow/moon/clouds/flowers/house/temple…)
//   scenes[].lines    — narration {text} or dialogue {who, text}; voices: vk tts ${slug}.html
//   scenes[].actions  — {who, do: enter|exit|walk|run|wave|cheer|point|talk|bow|surprise|think|look|sad|jump|face,
//                        arg, line} · {do:'shot', shot, on} · {do:'effect'} · {do:'sfx', kind} · {do:'hold', dur}
//                       (line = index of the line the action starts with; -1 = scene start)
//   cast[].look       — puppet look (hairStyle, cloth, trim, pants … colour names of the style's hues)
// Render: vk tts ${slug}.html && vk render ${slug}.html -o out/${slug}.mp4
const STORY = ${json};
const v = vk.film(STORY, { style: ${spec} });
</script>
</body></html>
`);
  fs.writeFileSync(path.join(dir, 'story' + (/^\s*\{/.test(src) ? '.json' : '.md')), src);
  const nLines = story.scenes.reduce((s, sc) => s + sc.lines.length, 0);
  console.log(`[vk make] ${story.scenes.length} scene(s), ${nLines} line(s), cast ${story.cast.map(c => c.id).join('/') || '—'}, style ${styles.join(' + ')}\n  → ${path.relative(process.cwd(), page)}`);
  if (opt.tts) { const m = await import('./tts.mjs'); await m.default([page]); }
  else console.log('  next: vk tts', path.relative(process.cwd(), page));
  if (opt.render) {
    const out = path.resolve(opt.mp4 || path.join(ROOT, 'out', slug + '.mp4'));
    const m = await import('./render.mjs'); await m.default([page, '-o', out]);
  } else console.log('  then: vk render', path.relative(process.cwd(), page), '-o', path.join('out', slug + '.mp4'));
  return page;
}
const esc = s => String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));
